language: rust

dist: bionic

arch:
  - amd64
  - arm64
  - s390x
  - ppc64le

rust:
  - nightly
  - beta
  - stable
  - 1.36.0

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo test --verbose

notifications:
  email: false
