language: rust

os: linux

dist: bionic

arch:
  - amd64

rust:
  - stable
  - 1.40.0
  - beta
  - nightly

jobs:
  include:
    - arch: arm64
    - arch: s390x
    - arch: ppc64le
    - os: osx
    - arch: amd64
      env: CARGO_BUILD_TARGET=i686-unknown-linux-gnu
      addons:
        apt:
          packages:
            - libc6-i386
            - lib32gcc1
            - gcc-multilib

  allow_failures:
    - rust: nightly

install:
  - ./scripts/rustup-extras.sh

script:
  - cargo test --verbose

notifications:
  email: false
