[package]
name = "lightning-sys"
version = "0.1.0"
authors = ["Peter Elliott <pelliott@ualberta.ca>"]
edition = "2018"
license = "GPL-3.0-or-later"
description = "GNU lightning bindings for rust"

[dependencies]
mashup = "0.1"
num-traits = "0.1"
libc = "0.2"

[build-dependencies]
bindgen = "0.50"
